### PR TITLE
test: Upcast the random numbers before computing their average

### LINKED ISSUE #3326: "test random uniform" fails for CPU backend
On macOS/Windows the CPP tests would fail with:

```console
$ DEVICE=cpu ./build/tests/tests -tc="test random uniform"
[doctest] doctest version is "2.4.12"
[doctest] run with "--help" for options
===============================================================================
/Users/zcbenz/codes/mlx/tests/random_tests.cpp:244:
TEST CASE:  test random uniform

/Users/zcbenz/codes/mlx/tests/random_tests.cpp:368: ERROR: CHECK( abs(float(mean(out).item<bfloat16_t>()) - 0.5f) < 0.02 ) is NOT correct!
  values: CHECK( 0.244141 <  0.02 )

===============================================================================
[doctest] test cases:  1 |  0 passed | 1 failed | 239 skipped
[doctest] assertions: 33 | 32 passed | 1 failed |
[doctest] Status: FAILURE!
```

which was caused by https://github.com/ml-explore/mlx/pull/2361, but I'm not exactly sure where the bug is. /cc @angeloskath

### PR DESCRIPTION
**Pull request by sofinvalery**
## Proposed changes

Accumulate CPU float16 and bfloat16 sum reductions in float32, while preserving the output dtype. This fixes precision loss in ops that use sum().

Fixes #3326.

## Checklist

Put an `x` in the boxes that apply.

- [x] I have read the CONTRIBUTING document
- [x] I have run pre-commit run --all-files to format my code / installed pre-commit prior to committing changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the necessary documentation (if needed)

### CODE REVIEW

**Comment by sofinvalery** [comment]
Made it inline. Feels cleaner.

**Review by zcbenz — CHANGES_REQUESTED** [review]
Allocating a new array would have heavy performance penalty, the correct way would be refactoring `strided_reduce`/`contiguous_reduce` to accumulate in float32 rather than the output type.

**Comment by sofinvalery** [comment]
Refactored `strided_reduce`/`contiguous_reduce` to support accumulation in a separate type.
float16/bfloat16 sums now accumulate in float32 without allocating a temp array.
Also added tests for reductions across full, contiguous, and strided axes.

File: mlx/backend/cpu/reduce.cpp [hunk 1]
```diff
@@ -135,27 +146,25 @@ void nd_loop(
...
+    *out_ptr = contiguous_reduce(in_ptr, x.size(), Op{}, init, init);
     return;
   }
 
   if (plan.type == ContiguousReduce && plan.shape.size() == 1) {
     int reduction_size = plan.shape[0];
     for (int i = 0; i < out.size(); i++, out_ptr++, in_ptr += reduction_size) {
-      *out_ptr = init;
-      contiguous_reduce(in_ptr, out_ptr, reduction_size, Op{}, init);
+      *out_ptr = contiguous_reduce(in_ptr, reduction_size, Op{}, init, init);
```
Comment (zcbenz) [inline mlx/backend/cpu/reduce.cpp]: Is it supposed to be:

```suggestion
      *out_ptr = contiguous_reduce(in_ptr, reduction_size, Op{}, *out_ptr, init);
```

File: mlx/backend/cpu/reduce.cpp [hunk 2]
```diff
@@ -96,19 +97,29 @@ void strided_reduce(
...
+  }
+  return accumulator;
+}
+
+template <typename T, typename U, typename Op>
+U contiguous_reduce(const T* x, int size, Op op, U accumulator, U init) {
   constexpr int N = std::min(simd::max_size<T>, simd::max_size<U>);
   simd::Simd<U, N> accumulator_v(init);
   while (size >= N) {
     accumulator_v = op(accumulator_v, simd::Simd<U, N>(simd::load<T, N>(x)));
```
Comment (zcbenz) [inline mlx/backend/cpu/reduce.cpp:103]: When building for macOS 14 it seems that we can't simply convert `Simd<float16>` to `Simd<float>`:

```
  /Users/runner/actions-runner/_work/mlx/mlx/mlx/backend/cpu/simd/accelerate_simd.h:63:40: error: no matching function for call to 'convert'
     63 |   Simd<T, N>(Simd<U, N> other) : value(asd::convert<scalar_t>(other.value)) {}
        |                                        ^~~~~~~~~~~~~~~~~~~~~~
  /Users/runner/actions-runner/_work/mlx/mlx/mlx/backend/cpu/reduce.cpp:113:39: note: in instantiation of function template specialization 'mlx::core::simd::Simd<float, 8>::Simd<__fp16>' requested here
    113 |     accumulator_v = op(accumulator_v, simd::Simd<U, N>(simd::load<T, N>(x)));
        |                                       ^
```

File: mlx/backend/cpu/reduce.cpp [hunk 3]
```diff
@@ -404,9 +450,9 @@ void reduce_dispatch_and_or(
     Reduce::ReduceType rtype,
     const std::vector<int>& axes) {
   if (rtype == Reduce::And) {
-    reduction_op<InT, bool, AndReduce>(in, out, axes, true);
+    reduction_op<InT, bool, AndReduce, bool>(in, out, axes, true);
```
Comment (zcbenz) [inline mlx/backend/cpu/reduce.cpp]: I prefer omitting the optional `AccT` so it would be obvious when the code is accumulating in a different type.

**Comment by angeloskath** [comment]
I don't think we should merge this tbh. It's kind of expected for floats that you get the accumulation precision of the float you are in.

I am not against choosing high precision temporaries internally if possible but given the current implementation it is actually faster to cast to float32 and then sum (didn't try it but almost certainly it will be).

For the test by the way, the correct fix is to simply upcast the random numbers before computing their average. We want to test random after all not sum.

**Comment by sofinvalery** [comment]
Updated the test only. Thanks for the feedback! @zcbenz @angeloskath

**Review by zcbenz — APPROVED** [review]
Thanks for fixing the test! Can you also update `.github/actions/test-windows/action.yml` to enable the test in CI?
