### ISSUE TITLE
Update nanobind pin

### ISSUE THREAD

**Issue by ngoldbaum** [ml-explore/mlx#2895]
nanobind is currently pinned to 2.4.0, which is about a year old. The current version is 2.10.2. I suspect the test failure I saw in #2807 will go away if we update nanobind.

When I try to build using an up-to-date nanobind version, the first compiler error I see is:

```
  /Users/goldbaum/Documents/mlx/python/src/small_vector.h:19:18: error: use of undeclared identifier 'NB_TYPING_TUPLE'
     19 |       const_name(NB_TYPING_TUPLE "[") + make_caster<Type>::Name +
        |                  ^
```

It looks like `NB_TYPING_TUPLE` was removed from nanobind when they dropped Python 3.8 support: https://github.com/wjakob/nanobind/commit/b50c3d80bab4f16ee57d680cab113925a7284880.

There are a lot more compiler errors after that so there might be other issues. Full build log: https://gist.github.com/ngoldbaum/421a8a7d4b251b6d8761c8a6dc42f38a

**Comment by ngoldbaum** [comment]
> I suspect the test failure I saw in https://github.com/ml-explore/mlx/issues/2807 will go away if we update nanobind.

No such luck it seems. Sent in #2896 anyway since it seems like it's worth doing.
