### ISSUE TITLE
[BUG] Error in 0.19.0 when prompt with adapter-path: 'types.SimpleNamespace' object has no attribute 'num_layers'.

### ISSUE THREAD

**Issue by hschaeufler** [ml-explore/mlx#1463]
**Describe the bug**
When I try to execute a prompt with the command below, the following error occurs. The problem has occurred since the update to 0.19.0. Before that the command worked. I suspect it is due to the loading of the adapter. If I leave out the adapter and only call generate for the model it works. The adapter was trained with the previous version. I don't know what it looks like if the adapter is also trained with 0.19.0.

```batch
dartgen %  mlx_lm.generate --model "meta-llama/Meta-Llama-3.1-8B-Instruct" \
    --adapter-path "results/llama3_1_8B_instruct_lora/tuning_03/adapters" \
    --max-tokens 4000 \
    --prompt "Say hello to me"

Fetching 11 files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11/11 [00:00<00:00, 30574.78it/s]
Traceback (most recent call last):
  File "/Users/admin/.local/share/virtualenvs/dartgen-xL9Vbcux/bin/mlx_lm.generate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/admin/.local/share/virtualenvs/dartgen-xL9Vbcux/lib/python3.12/site-packages/mlx_lm/generate.py", line 178, in main
    model, tokenizer = load(
                       ^^^^^
  File "/Users/admin/.local/share/virtualenvs/dartgen-xL9Vbcux/lib/python3.12/site-packages/mlx_lm/utils.py", line 516, in load
    model = load_adapters(model, adapter_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/.local/share/virtualenvs/dartgen-xL9Vbcux/lib/python3.12/site-packages/mlx_lm/tuner/utils.py", line 179, in load_adapters
    config.num_layers,
    ^^^^^^^^^^^^^^^^^
AttributeError: 'types.SimpleNamespace' object has no attribute 'num_layers'. Did you mean: 'lora_layers'?
```

**To Reproduce**

Include code snippet
```python
mlx_lm.generate --model "meta-llama/Meta-Llama-3.1-8B-Instruct" \
    --adapter-path "results/llama3_1_8B_instruct_lora/tuning_03/adapters" \
    --max-tokens 4000 \       
    --prompt "Say hello to me"
```

**Expected behavior**
Model gives an answer and not an Error.

**Desktop (please complete the following information):**
 - OS Version: MacOS 14.16.1
 - MLX-LM Version: 0.19.0

**Additional context**
I think the problem is that in the extension for full parameter tuning the line https://github.com/ml-explore/mlx-examples/blob/50e5ca81a8c06f4c49cec48795330209a885d2c9/llms/mlx_lm/tuner/utils.py#L179 was adjusted and config.num_layers was entered instead of config.lora_layers.

**Comment by awni** [comment]
Yes that was changed when we introduced full fine-tuning as the name `config.lora_layers` didn't make sense anymore.

You can fix it by editing: `results/llama3_1_8B_instruct_lora/tuning_03/adapters/adapter_config.json`. Change `lora_layers` to `num_layers`. Sorry for the compatibility issue.

**Comment by hschaeufler** [comment]
> Yes that was changed when we introduced full fine-tuning as the name `config.lora_layers` didn't make sense anymore.
> 
> You can fix it by editing: `results/llama3_1_8B_instruct_lora/tuning_03/adapters/adapter_config.json`. Change `lora_layers` to `num_layers`. Sorry for the compatibility issue.

Ah thanks for the quick answer and solution. Do I have to adjust other parameters like lora_parameters as well? 

Wouldn't it be maybe an option to make this backwards compatible to adapt the position as follows and, if necessary, issue a warning or are other places in the scripts also affected?? 
```
    if fine_tune_type != "full":
        linear_to_lora_layers(
            model,
            config.num_layers or config.lora_layers,
            config.lora_parameters,
            use_dora=(fine_tune_type == "dora"),
        )
```

**Comment by awni** [comment]
> Ah thanks for the quick answer and solution. Do I have to adjust other parameters like lora_parameters as well?

I think the `num_layers` is the only thing that needs to change.

> Wouldn't it be maybe an option to make this backwards compatible to adapt the position as follows and, if necessary, issue a warning or are other places in the scripts also affected??

Indeed, we could do something like that.

**Comment by hschaeufler** [comment]
Ok, thank you. I have adapted my `adapter_config.json`. The query now works. :)
