### PR TITLE
Update nanobind pin to most recent version

### LINKED ISSUE #2895: Update nanobind pin
nanobind is currently pinned to 2.4.0, which is about a year old. The current version is 2.10.2. I suspect the test failure I saw in #2807 will go away if we update nanobind.

When I try to build using an up-to-date nanobind version, the first compiler error I see is:

```
  /Users/goldbaum/Documents/mlx/python/src/small_vector.h:19:18: error: use of undeclared identifier 'NB_TYPING_TUPLE'
     19 |       const_name(NB_TYPING_TUPLE "[") + make_caster<Type>::Name +
        |                  ^
```

It looks like `NB_TYPING_TUPLE` was removed from nanobind when they dropped Python 3.8 support: https://github.com/wjakob/nanobind/commit/b50c3d80bab4f16ee57d680cab113925a7284880.

There are a lot more compiler errors after that so there might be other issues. Full build log: https://gist.github.com/ngoldbaum/421a8a7d4b251b6d8761c8a6dc42f38a

### PR DESCRIPTION
**Pull request by ngoldbaum**
## Proposed changes

Fixes #2895.

The current pin is about a year old. Assuming the CI passes it seems prudent to me to update it.

`NB_TYPING_TUPLE` is not necessary on Python 3.9 and newer.

## Checklist

Put an `x` in the boxes that apply.

- [x] I have read the [CONTRIBUTING](https://github.com/ml-explore/mlx/blob/main/CONTRIBUTING.md) document
- [x] I have run `pre-commit run --all-files` to format my code / installed pre-commit prior to committing changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have updated the necessary documentation (if needed)

### CODE REVIEW

**Comment by awni** [comment]
Bump that as well: https://github.com/ml-explore/mlx/blob/main/examples/extensions/pyproject.toml#L5-L6

**Comment by awni** [comment]
And that https://github.com/ml-explore/mlx/blob/main/setup.py#L258

**Comment by awni** [comment]
And there are a few places it's hardcoded in our CI: 

```
grep -r nanobind .github/*
```

**Comment by ngoldbaum** [comment]
Thanks for pointing that out, I think I got them all:

```
goldbaum at Nathans-MBP in ~/Documents/mlx on nanobind
± grep -r "2\.4\.0"

goldbaum at Nathans-MBP in ~/Documents/mlx on nanobind
± grep -r "2\.10\.2"
./pyproject.toml:  "nanobind==2.10.2",
./setup.py:            "nanobind==2.10.2",
./examples/extensions/requirements.txt:nanobind==2.10.2
./examples/extensions/pyproject.toml:  "nanobind==2.10.2",
./.github/workflows/release.yml:          pip install cmake setuptools nanobind==2.10.2
./.github/actions/setup-linux/action.yml:        pip install setuptools cmake nanobind==2.10.2
./.github/actions/build-macos/action.yml:        pip install cmake setuptools nanobind==2.10.2
```

**Comment by ngoldbaum** [comment]
Building on the GIL-enabled build I also see:

```
 /Users/goldbaum/Documents/mlx-gil/python/src/mlx_func.cpp:92:62: error: use of undeclared identifier 'NB_HAVE_VECTORCALL'
     92 |     /* .flags = */ Py_TPFLAGS_DEFAULT | Py_TPFLAGS_HAVE_GC | NB_HAVE_VECTORCALL,
        |                                                              ^
```

So I'll have to fix that one too.

**Comment by awni** [comment]
Actually looks like the lint checks failed. Can you run the pre-commit hooks?

**Comment by ngoldbaum** [comment]
Thanks for bearing with me. I might turn actions on for my fork so I can at least run the tests without pinging you.
