### ISSUE TITLE
"test random uniform" fails for CPU backend

### ISSUE THREAD

**Issue by zcbenz** [ml-explore/mlx#3326]
On macOS/Windows the CPP tests would fail with:

```console
$ DEVICE=cpu ./build/tests/tests -tc="test random uniform"
[doctest] doctest version is "2.4.12"
[doctest] run with "--help" for options
===============================================================================
/Users/zcbenz/codes/mlx/tests/random_tests.cpp:244:
TEST CASE:  test random uniform

/Users/zcbenz/codes/mlx/tests/random_tests.cpp:368: ERROR: CHECK( abs(float(mean(out).item<bfloat16_t>()) - 0.5f) < 0.02 ) is NOT correct!
  values: CHECK( 0.244141 <  0.02 )

===============================================================================
[doctest] test cases:  1 |  0 passed | 1 failed | 239 skipped
[doctest] assertions: 33 | 32 passed | 1 failed |
[doctest] Status: FAILURE!
```

which was caused by https://github.com/ml-explore/mlx/pull/2361, but I'm not exactly sure where the bug is. /cc @angeloskath

**Comment by sofinvalery** [comment]
This probably happens because accumulating sum for mean in bfloat16 is numerically unstable for this reduction size. Accumulating bfloat16 reductions internally in float32 would fix the precision loss. 
Jax does this for float16/bfloat16 reductions, not sure about torch.
